openapi: 3.0.3
info: { title: HIS Cell API, version: 1.0.0 }
servers: [{ url: /api/v1/his }]
paths:
  /health:
    get:
      responses: { '200': { description: OK } }
  /patients:
    get:
      parameters: [{ name: X-Tenant-Id, in: header, required: true }]
      responses: { '200': { description: OK } }
    post:
      parameters: [{ name: X-Request-ID, in: header, required: true }, { name: X-Tenant-Id, in: header, required: true }]
      requestBody: { content: { application/json: { schema: { type: object } } } }
      responses: { '201': { description: Created } }
  /visits:
    get:
      parameters: [{ name: X-Tenant-Id, in: header, required: true }]
      responses: { '200': { description: OK } }
    post:
      parameters: [{ name: X-Request-ID, in: header }, { name: X-Tenant-Id, in: header }]
      requestBody: { content: { application/json: { schema: { type: object } } } }
      responses: { '201': { description: Created } }
  /registration:
    get:
      parameters: [{ name: X-Tenant-Id, in: header }, { name: patientId, in: query }]
      responses: { '200': { description: OK } }
    post:
      parameters: [{ name: X-Tenant-Id, in: header }]
      requestBody: { content: { application/json: { schema: { type: object } } } }
      responses: { '201': { description: Created } }
  /prescriptions:
    post:
      parameters: [{ name: X-Tenant-Id, in: header }]
      requestBody: { content: { application/json: { schema: { type: object } } } }
      responses: { '201': { description: Created } }
  /charges:
    get:
      parameters: [{ name: X-Tenant-Id, in: header }, { name: visitId, in: query }]
      responses: { '200': { description: OK } }
    post:
      parameters: [{ name: X-Tenant-Id, in: header }]
      requestBody: { content: { application/json: { schema: { type: object } } } }
      responses: { '201': { description: Created } }
  /inpatients:
    get:
      parameters: [{ name: X-Tenant-Id, in: header }, { name: patientId, in: query }]
      responses: { '200': { description: OK } }
    post:
      parameters: [{ name: X-Request-ID, in: header }, { name: X-Tenant-Id, in: header }]
      requestBody: { content: { application/json: { schema: { type: object } } } }
      responses: { '201': { description: Created } }
  /medical-records:
    get:
      parameters: [{ name: X-Tenant-Id, in: header }, { name: patientId, in: query }]
      responses: { '200': { description: OK } }
    post:
      parameters: [{ name: X-Tenant-Id, in: header }]
      requestBody: { content: { application/json: { schema: { type: object } } } }
      responses: { '201': { description: Created } }
  /orders:
    get:
      parameters: [{ name: X-Tenant-Id, in: header }]
      responses: { '200': { description: OK } }
    post:
      parameters: [{ name: X-Request-ID, in: header }, { name: X-Tenant-Id, in: header }]
      requestBody: { content: { application/json: { schema: { type: object } } } }
      responses: { '201': { description: Created } }
  /audit-logs:
    get:
      parameters: [{ name: X-Tenant-Id, in: header }]
      responses: { '200': { description: OK } }
components:
  schemas: { Error: { type: object, properties: { code: {}, message: {}, requestId: {} } } }
  securitySchemes: { BearerAuth: { type: http, scheme: bearer, bearerFormat: JWT } }
security: [{ BearerAuth: [] }]
