openapi: 3.0.3
info: { title: LIS Cell API, version: 1.0.0 }
servers: [{ url: /api/v1/lis }]
paths:
  /health:
    get:
      responses: { '200': { description: OK } }
  /test-requests:
    get:
      parameters: [{ name: X-Tenant-Id, in: header }]
      responses: { '200': { description: OK } }
    post:
      parameters: [{ name: X-Request-ID, in: header }, { name: X-Tenant-Id, in: header }]
      requestBody: { content: { application/json: { schema: { type: object } } } }
      responses: { '201': { description: Created } }
  /samples:
    get:
      parameters: [{ name: X-Tenant-Id, in: header }]
      responses: { '200': { description: OK } }
    post:
      parameters: [{ name: X-Request-ID, in: header }, { name: X-Tenant-Id, in: header }]
      requestBody: { content: { application/json: { schema: { type: object } } } }
      responses: { '201': { description: Created } }
  /samples/{sampleId}/receive:
    post:
      parameters: [{ name: X-Tenant-Id, in: header }]
      responses: { '200': { description: OK }, '404': { description: Not Found } }
  /results:
    get:
      parameters: [{ name: X-Tenant-Id, in: header }]
      responses: { '200': { description: OK } }
    post:
      parameters: [{ name: X-Request-ID, in: header }, { name: X-Tenant-Id, in: header }]
      requestBody: { content: { application/json: { schema: { type: object } } } }
      responses: { '201': { description: Created } }
  /reports:
    get:
      parameters: [{ name: X-Tenant-Id, in: header }]
      responses: { '200': { description: OK } }
    post:
      parameters: [{ name: X-Request-ID, in: header }, { name: X-Tenant-Id, in: header }]
      requestBody: { content: { application/json: { schema: { type: object } } } }
      responses: { '201': { description: Created } }
  /reports/{reportId}/review:
    post:
      parameters: [{ name: X-Tenant-Id, in: header }]
      responses: { '200': { description: OK }, '404': { description: Not Found } }
  /reports/{reportId}/publish:
    post:
      parameters: [{ name: X-Tenant-Id, in: header }]
      responses: { '200': { description: OK }, '404': { description: Not Found } }
  /reports/{reportId}/audits:
    get:
      parameters: [{ name: X-Tenant-Id, in: header }]
      responses: { '200': { description: OK } }
  /audit-logs:
    get:
      parameters: [{ name: X-Tenant-Id, in: header }]
      responses: { '200': { description: OK } }
components:
  schemas: { Error: { type: object, properties: { code: {}, message: {}, requestId: {} } } }
  securitySchemes: { BearerAuth: { type: http, scheme: bearer, bearerFormat: JWT } }
security: [{ BearerAuth: [] }]
